<a href="https://colab.research.google.com/github/vvrgit/ML-Optimization/blob/main/Logistic_Regression_CovidData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Mount Google Drive**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import math as mt
import random
import pandas as pd

In [3]:
data=pd.read_excel("/content/drive/MyDrive/AI Data/LR-Data.xlsx")
data.head()

Fever   O2  Cold   Cough  Covid
0   98.0  100      0      0      0
1   98.3   99      0      0      0
2   98.6   98      0      0      0
3   97.0  100      0      0      0
4  100.0   90      1      1      1

In [4]:
Fever_min=data['Fever'].min()
Fever_max=data['Fever'].max()
O2_min=data['O2'].min()
O2_max=data['O2'].max()

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(data)
data_norm=scaler.transform(data)
data_norm

array([[0.1 , 1.  , 0.  , 0.  , 0.  ],
       [0.13, 0.95, 0.  , 0.  , 0.  ],
       [0.16, 0.9 , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  ],
       [0.3 , 0.5 , 1.  , 1.  , 1.  ],
       [0.5 , 0.3 , 1.  , 1.  , 1.  ],
       [0.8 , 0.4 , 1.  , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  , 1.  ]])

In [6]:
import pandas as pd
data_norm=pd.DataFrame(data_norm,columns=['Fever','O2','Cold','Cough','Covid'])
data_norm.head()

Fever    O2  Cold  Cough  Covid
0   0.10  1.00   0.0    0.0    0.0
1   0.13  0.95   0.0    0.0    0.0
2   0.16  0.90   0.0    0.0    0.0
3   0.00  1.00   0.0    0.0    0.0
4   0.30  0.50   1.0    1.0    1.0

In [7]:
from sklearn.model_selection import train_test_split
dataframe = data_norm.values
X, y = dataframe[:, :-1], dataframe[:, -1]
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 10)
x_train

array([[0.8 , 0.4 , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  ],
       [0.1 , 1.  , 0.  , 0.  ],
       [0.3 , 0.5 , 1.  , 1.  ],
       [0.5 , 0.3 , 1.  , 1.  ],
       [0.13, 0.95, 0.  , 0.  ]])

In [8]:
m1=random.uniform(-10,10)
m2=random.uniform(-10,10)
m3=random.uniform(-10,10)
m4=random.uniform(-10,10)
c=random.uniform(-10,10)
eta=0.1
max_iter=10000

In [9]:
for iter in range(max_iter):
  for sample in range(x_train.shape[0]):
    net=m1*x_train[sample,0]+m2*x_train[sample,1]+m3*x_train[sample,2]+m4*x_train[sample,3]+c
    yp=1/(1+np.exp(-net))
    m1=m1+eta*(y_train[sample]-yp)*x_train[sample,0]
    m2=m2+eta*(y_train[sample]-yp)*x_train[sample,1]
    m3=m3+eta*(y_train[sample]-yp)*x_train[sample,2]
    m4=m4+eta*(y_train[sample]-yp)*x_train[sample,3]
    c=c+eta*(y_train[sample]-yp)
print('model parameter m and c',m1,m2,m3,m4,c)

model parameter m and c 4.0837074638212005 -10.572546576933508 1.518876698954882 7.4180497584248455 2.3253207923972963


In [10]:
Fever=input('enter Fever value')
O2=input('enter O2 value')
cold=input('enter cold value')
cough=input('enter cough value')
print('Fever=',Fever)
print('O2=',O2)
print('cold=',cold)
print('cough=',cough)


F_norm=(float(Fever)-Fever_min)/(Fever_max-Fever_min)
O2_norm=(float(O2)-O2_min)/(O2_max-O2_min)
net=m1*float(F_norm)+m2*float(O2_norm)+m3*float(cold)+m4*float(cough)+c
yp=1/(1+np.exp(-net))
print('Y=',round(yp))
if(yp>0.5):
  print("Covid Positive")
else:
  print("Covid Negative")

enter Fever value110
enter O2 value80
enter cold value1
enter cough value1
Fever= 110
O2= 80
cold= 1
cough= 1
Y= 1
Covid Positive


In [11]:
import numpy as np
import math as mt
import random
import pandas as pd

In [12]:
data=pd.read_excel("/content/drive/MyDrive/AI Data/LR-Data.xlsx")
data.head()

Fever   O2  Cold   Cough  Covid
0   98.0  100      0      0      0
1   98.3   99      0      0      0
2   98.6   98      0      0      0
3   97.0  100      0      0      0
4  100.0   90      1      1      1

In [13]:
Fever_min=data['Fever'].min()
Fever_max=data['Fever'].max()
O2_min=data['O2'].min()
O2_max=data['O2'].max()

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(data)
data_norm=scaler.transform(data)
data_norm

array([[0.1 , 1.  , 0.  , 0.  , 0.  ],
       [0.13, 0.95, 0.  , 0.  , 0.  ],
       [0.16, 0.9 , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  ],
       [0.3 , 0.5 , 1.  , 1.  , 1.  ],
       [0.5 , 0.3 , 1.  , 1.  , 1.  ],
       [0.8 , 0.4 , 1.  , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  , 1.  ]])

In [15]:
import pandas as pd
data_norm=pd.DataFrame(data_norm,columns=['Fever','O2','Cold','Cough','Covid'])
data_norm.head()

Fever    O2  Cold  Cough  Covid
0   0.10  1.00   0.0    0.0    0.0
1   0.13  0.95   0.0    0.0    0.0
2   0.16  0.90   0.0    0.0    0.0
3   0.00  1.00   0.0    0.0    0.0
4   0.30  0.50   1.0    1.0    1.0

In [16]:
from sklearn.model_selection import train_test_split
dataframe = data_norm.values
X, y = dataframe[:, :-1], dataframe[:, -1]
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 10)
x_train

array([[0.8 , 0.4 , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  ],
       [0.1 , 1.  , 0.  , 0.  ],
       [0.3 , 0.5 , 1.  , 1.  ],
       [0.5 , 0.3 , 1.  , 1.  ],
       [0.13, 0.95, 0.  , 0.  ]])

In [19]:
m1=random.uniform(-10,10)
m2=random.uniform(-10,10)
m3=random.uniform(-10,10)
m4=random.uniform(-10,10)
c=random.uniform(-10,10)
eta=0.1
max_iter=10000
ssg_m1 = 0
ssg_m2 = 0
ssg_m3 = 0
ssg_m4 = 0

ssg_c = 0
eps=mt.pow(10,-8)

In [20]:
def gradient(m1,m2,m3,m4,c,x1,x2,x3,x4,y):
  net=m1*x1+m2*x2+m3*x3+m4*x4+c
  yp=1/(1+np.exp(-net))
  m1_deriv=-1*(y-yp)*x1
  m2_deriv=-1*(y-yp)*x2
  m3_deriv=-1*(y-yp)*x3
  m4_deriv=-1*(y-yp)*x4
  c_deriv=-1*(y-yp)
  return m1_deriv,m2_deriv,m3_deriv,m4_deriv,c_deriv

In [23]:
for iter in range(max_iter):
  del_m1,del_m2,del_m3,del_m4,del_c=0.0,0.0,0.0,0.0,0.0
  for sample in range(x_train.shape[0]):
    x1=x_train[sample,0]
    x2=x_train[sample,1]
    x3=x_train[sample,2]
    x4=x_train[sample,3]
    y=y_train[sample]
    delm1,delm2,delm3,delm4,delc=gradient(m1,m2,m3,m4,c,x1,x2,x3,x4,y)
    del_m1=del_m1+delm1
    del_m2=del_m2+delm2
    del_m3=del_m3+delm3
    del_m4=del_m4+delm4
    del_c=del_c+delc

  del_m1=del_m1/len(x_train)
  del_m2=del_m2/len(x_train)
  del_m3=del_m3/len(x_train)
  del_m4=del_m4/len(x_train)
  del_c=del_c/len(x_train)

  ssg_m1=ssg_m1+(del_m1*del_m1)
  ssg_m2=ssg_m2+(del_m2*del_m2)
  ssg_m3=ssg_m3+(del_m3*del_m3)
  ssg_m4=ssg_m4+(del_m4*del_m4)
  ssg_c=ssg_c+(del_c*del_c)

  m1=m1-(eta*del_m1)/(mt.sqrt(ssg_m1+eps))
  m2=m2-(eta*del_m2)/(mt.sqrt(ssg_m2+eps))
  m3=m3-(eta*del_m3)/(mt.sqrt(ssg_m3+eps))
  m4=m4-(eta*del_m4)/(mt.sqrt(ssg_m4+eps))
  c=c-(eta*del_c)/(mt.sqrt(ssg_c+eps))
  #print(f"Iteration: {iter}\tValue of m: {m}, \tValue of c: {c}")

print(f"\nThe local minima occurs at: {m1},{m2},{m3},{m4},{c}")


The local minima occurs at: -0.4212684502730247,-9.421537982754463,2.5118940708815662,-0.9172709030637263,6.090999436608072


In [25]:
Fever=input('enter Fever value')
O2=input('enter O2 value')
cold=input('enter cold value')
cough=input('enter cough value')
print('Fever=',Fever)
print('O2=',O2)
print('cold=',cold)
print('cough=',cough)


F_norm=(float(Fever)-Fever_min)/(Fever_max-Fever_min)
O2_norm=(float(O2)-O2_min)/(O2_max-O2_min)
net=m1*float(F_norm)+m2*float(O2_norm)+m3*float(cold)+m4*float(cough)+c
yp=1/(1+np.exp(-net))
print('Y=',round(yp))
if(yp>0.5):
  print("Covid Positive")
else:
  print("Covid Negative")

enter Fever value98
enter O2 value100
enter cold value0
enter cough value0
Fever= 98
O2= 100
cold= 0
cough= 0
Y= 0
Covid Negative
