<a href="https://colab.research.google.com/github/vvrgit/ML-Optimization/blob/main/Simple_ANN_With_SGD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ANN Without Hidden Layer and with non-linear activation functions and bias**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# **Import Libraries**

In [2]:
import pandas as pd
import numpy as np

# **Data Loading**

In [12]:
data=pd.read_excel("/content/drive/MyDrive/NNDL-Data/Sample_Data_Sigmoid.xlsx")
data.head()

A    B    C         X
0  0.1  0.2  0.3  0.967705
1  0.2  0.3  0.4  0.947846
2  0.3  0.4  0.5  0.916827
3  0.4  0.5  0.6  0.869892
4  0.5  0.6  0.7  0.802184

# **Data Split**

In [13]:
#Train-Test Split
from sklearn.model_selection import train_test_split
data_train,data_test=train_test_split(data,test_size=0.05,random_state=1)
q1=len(data_train)
q2=len(data_test)
data_train=np.array(data_train)
data_test=np.array(data_test)

# **Random Weight & Bias Initialization**

In [21]:
#Random Weight Initialization
weights=np.random.uniform(-10,10,size=(3,1))
bias=np.random.uniform(-10,10,size=(1,1))
print(weights)
print(bias)

[[ 9.44092873]
 [-2.01094511]
 [-7.60342239]]
[[-2.28704624]]


# **ANN Training With SGD**

In [23]:
l=0.9
for i in range(10000):
    for j in range(q1):
        z=np.dot(data_train[j,0:3],weights)+bias #n.shape-1,1
        o=1/(1+np.exp(-z))
        dw=(l*(data_train[[j],3]-o))*o*(1-o)*data_train[[j],0:3].T
        db=(l*(data_train[[j],3]-o))*o*(1-o)
        weights=weights+dw
        bias=bias+db
print(bias)
print(weights)

[[5.93989626]]
[[ 7.00938074]
 [-3.61979885]
 [-8.38958189]]


# **Prediction on Test Data**

In [16]:
pred_test=np.zeros((q2,1))
for j in range(q2):
    z=np.dot(data_test[j,0:3],weights)+bias #n.shape-1,
    o=1/(1+np.exp(-z))
    pred_test[j]=o
pred_test

array([[0.59909432]])

# **Testing Error**

In [17]:
from sklearn.metrics import mean_squared_error
print("Testing MSE:",mean_squared_error(data_test[:,3],pred_test))

Testing MSE: 1.6537459777053476e-07


# **Predictions on Training Data**

In [18]:
pred_train=np.zeros((q1,1))
for j in range(q1):
    z=np.dot(data_train[j,0:3],weights)+bias #n.shape-1,
    o=1/(1+np.exp(-z))
    pred_train[j]=o
pred_train

array([[0.91666281],
       [0.94769213],
       [0.96757681],
       [0.80214721],
       [0.86975642],
       [0.71109967]])

# **Training Error**

In [19]:
from sklearn.metrics import mean_squared_error
print("Training MSE:",mean_squared_error(data_train[:,3],pred_train))

Training MSE: 1.8221863354187917e-08


# **Deployment**

In [20]:
inputvector=np.zeros((1,3))
for j in range(3):
  A=input("enter value")
  inputvector[0,j]=A
z=np.dot(inputvector[0,0:3],weights)+bias
Pred=1/(1+np.exp(-z))
print("Predicted Output:",Pred)

enter value0.1
enter value0.2
enter value0.3
Predicted Output: [[0.96757681]]


# **Thank You**